name: Generate Pac-Man Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Gera o Pacman SVG a partir da ação original do criador
      - name: Generate Pacman SVG
        uses: abhisheknaiidu/pacman-contribution-graph@master
        with:
          github_user_name: FontouraC18H22O2

      # Envia o SVG para o branch de output
      - name: Push Pacman SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: github-contribution-grid-snake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
